# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk8

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту Bul290896@yandex.ru если сборка упала
notifications:
  email:
    recipients:
      -Bul290896@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
    env:
      global:
        - CODECOV_TOKEN="e7a8c165-8c03-4194-915d-6639a4cff602"